export const PREPOPULATE_MOVIES = "PREPOPULATE_MOVIES";
export const ADD_MOVIE = "ADD_MOVIE";
export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const FILTER_MOVIETITLE = "FILTER_MOVIETITLE";
export const FILTER_GENRE = "FILTER_GENRE";
